spring:
  batch:
    job:
      enabled: ${BATCH_JOB_ENABLED:false}
      name: healthCheckJob
    jdbc:
      initialize-schema: always

batch:
  schedules:
    weekly-family-recap:
      enabled: ${BATCH_WEEKLY_FAMILY_RECAP_ENABLED:false}
      cron: ${BATCH_WEEKLY_FAMILY_RECAP_CRON:0 10 0 * * MON}
    monthly-family-recap:
      enabled: ${BATCH_MONTHLY_FAMILY_RECAP_ENABLED:false}
      cron: ${BATCH_MONTHLY_FAMILY_RECAP_CRON:0 20 0 1 * *}
    monthly-usage-reset:
      enabled: ${BATCH_MONTHLY_USAGE_RESET_ENABLED:false}
      cron: ${BATCH_MONTHLY_USAGE_RESET_CRON:0 1 0 1 * *}
    db-redis-reconciliation:
      enabled: ${BATCH_DB_REDIS_RECONCILIATION_ENABLED:false}
      cron: ${BATCH_DB_REDIS_RECONCILIATION_CRON:0 0 3 * * *}
  jobs:
    weekly-family-recap:
      lock-ttl: ${BATCH_WEEKLY_FAMILY_RECAP_LOCK_TTL:PT1H}
      chunk-size: ${BATCH_WEEKLY_FAMILY_RECAP_CHUNK_SIZE:1000}
      db-fetch-size: ${BATCH_WEEKLY_FAMILY_RECAP_DB_FETCH_SIZE:1000}
    monthly-family-recap:
      lock-ttl: ${BATCH_MONTHLY_FAMILY_RECAP_LOCK_TTL:PT1H}
      chunk-size: ${BATCH_MONTHLY_FAMILY_RECAP_CHUNK_SIZE:1000}
      db-fetch-size: ${BATCH_MONTHLY_FAMILY_RECAP_DB_FETCH_SIZE:1000}
    monthly-usage-reset:
      lock-ttl: ${BATCH_MONTHLY_USAGE_RESET_LOCK_TTL:PT1H}
      redis-chunk-size: ${BATCH_MONTHLY_USAGE_RESET_REDIS_CHUNK_SIZE:2000}
      db-fetch-size: ${BATCH_MONTHLY_USAGE_RESET_DB_FETCH_SIZE:4000}
    db-redis-reconciliation:
      lock-ttl: ${BATCH_DB_REDIS_RECONCILIATION_LOCK_TTL:PT1H}
      redis-chunk-size: ${BATCH_DB_REDIS_RECONCILIATION_REDIS_CHUNK_SIZE:2000}
      db-fetch-size: ${BATCH_DB_REDIS_RECONCILIATION_DB_FETCH_SIZE:4000}
